---
- name: Set up node with node exporter and Nginx
  hosts: worker
  become: true
  roles:
    - node_exporter
    - nginx

- name: Set up VictoriaMetrics node
  hosts: victoriametrics
  become: true
  roles:
    - victoriametrics
    - node_exporter

- name: Set up Prometheus node
  hosts: prometheus
  become: true
  roles:
    - prometheus
    - node_exporter

- name: Set up monitoring node
  hosts: master-monitoring
  become: true
  roles:
    - prometheus_master
    - grafana