---
- name: Set up node with node exporter and Nginx
  hosts: worker
  become: true
  tasks:

- name: Set up VictoriaMetrics node
  hosts: victoriametrics
  become: true
  tasks: 

- name: Set up Prometheus node
  hosts: prometheus
  become: true
  tasks: 

- name: Set up monitoring node
  hosts: master-monitoring
  become: true
  tasks: 