---
- name: Download Prometheus binary
  ansible.builtin.get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v3.10.0/prometheus-3.10.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Create prometheus system group
  ansible.builtin.group:
    name: prometheus
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: prometheus
    group: prometheus
    state: present
    shell: /sbin/nologin

- name: Unarchive Prometheus binary
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt
    remote_src: true
    mode: 0744
    owner: prometheus
    group: prometheus

- name: Template Prometheus systemd service
  ansible.builtin.template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service

- name: Configure /etc/hosts
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for n in range(prometheus_host_number) %}
      192.168.10.10 host-{{ n }}
      {% endfor %}
    insertafter: EOF

- name: Create the /etc/prometheus directory
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    group: prometheus
    owner: prometheus

- name: Deploy prometheus.yml configuration file
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: Create /data directory
  ansible.builtin.file:
    path: /data
    state: directory
    group: prometheus
    owner: prometheus

- name: Ensure Prometheus systemd service is enabled
  ansible.builtin.systemd_service:
    name: prometheus
    state: restarted
    enabled: true
    daemon_reload: true