all:
  children:
    nodes:
      hosts:
        worker:
          ansible_host: 192.168.10.10
        victoriametrics:
          ansible_host: 192.168.10.20
        prometheus:
          ansible_host: 192.168.10.30
        master-monitoring:
          ansible_host: 89.169.183.24
      vars:
        ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q dev@89.169.183.24"'
